import type {
  RegressionAssertion,
  RegressionLocator,
  RegressionTestSpec,
} from '../domain/regression.js';

export function typescriptString(value: string): string {
  return JSON.stringify(value).replaceAll(
    /[\u007f-\u009f\u2028\u2029]/g,
    (character) => `\\u${character.codePointAt(0)?.toString(16).padStart(4, '0') ?? '0000'}`,
  );
}

function idSelector(value: string): string {
  return `[id="${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"]`;
}

function caseInsensitiveExactName(value: string): string {
  const pattern = `^${value.replaceAll(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`;
  return `new RegExp(${typescriptString(pattern)}, "i")`;
}

export function renderLocator(locator: RegressionLocator): string {
  switch (locator.strategy) {
    case 'testId':
      return `page.getByTestId(${typescriptString(locator.value)})`;
    case 'role':
      return `page.getByRole(${typescriptString(locator.role)}, { name: ${typescriptString(locator.name)}, exact: true })`;
    case 'label':
      return `page.getByLabel(${typescriptString(locator.value)}, { exact: true })`;
    case 'id':
      return `page.locator(${typescriptString(idSelector(locator.value))})`;
    case 'text':
      return `page.getByText(${typescriptString(locator.value)}, { exact: true })`;
  }
}

export function regressionAssertionDescription(assertion: RegressionAssertion): string {
  switch (assertion.kind) {
    case 'URL':
      return `URL equals ${assertion.url}`;
    case 'VISIBLE_ROLE':
      return `${assertion.role} "${assertion.name}" is visible`;
    case 'ATTRIBUTE':
      return `${assertion.attribute} equals ${assertion.value}`;
    case 'HTTP_NO_SERVER_ERROR':
      return `${assertion.method} ${assertion.url} returns below 500`;
  }
}

export class RegressionTypeScriptRenderer {
  public render(spec: RegressionTestSpec): string {
    const http = spec.assertions.find(
      (assertion): assertion is Extract<RegressionAssertion, { kind: 'HTTP_NO_SERVER_ERROR' }> =>
        assertion.kind === 'HTTP_NO_SERVER_ERROR',
    );
    const declaration = spec.mode === 'FIXME' ? 'test.fixme' : 'test';
    const lines = [
      '// Generated by Agentic QA.',
      `// Finding: ${spec.findingId}`,
      `// Verdict: ${spec.metadata.verdict}`,
      `// Source verification: ${spec.metadata.verificationId}`,
      '// Review before committing to an application repository.',
      '',
      "import { expect, test } from '@playwright/test';",
      '',
      `${declaration}(${typescriptString(spec.title)}, async ({ page }) => {`,
    ];
    for (let index = 0; index < spec.steps.length; index += 1) {
      const step = spec.steps[index];
      if (step === undefined) continue;
      if (index === spec.triggerStepIndex && http !== undefined) {
        lines.push(
          '  const responsePromise = page.waitForResponse(',
          `    (response) => response.url() === ${typescriptString(http.url)} && response.request().method() === ${typescriptString(http.method)},`,
          '  );',
          '',
        );
      }
      if (step.kind === 'NAVIGATE') {
        lines.push(`  await page.goto(${typescriptString(step.url)});`);
      } else {
        lines.push(`  await ${renderLocator(step.locator)}.click();`);
      }
      if (index < spec.steps.length - 1) lines.push('');
    }
    if (spec.steps.length > 0) lines.push('');
    for (const assertion of spec.assertions) {
      switch (assertion.kind) {
        case 'URL':
          lines.push(`  await expect(page).toHaveURL(${typescriptString(assertion.url)});`);
          break;
        case 'VISIBLE_ROLE':
          lines.push(
            `  await expect(page.getByRole(${typescriptString(assertion.role)}, { name: ${caseInsensitiveExactName(assertion.name)} })).toBeVisible();`,
          );
          break;
        case 'ATTRIBUTE':
          lines.push(
            `  await expect(${renderLocator(assertion.locator)}).toHaveAttribute(${typescriptString(assertion.attribute)}, ${typescriptString(assertion.value)});`,
          );
          break;
        case 'HTTP_NO_SERVER_ERROR':
          lines.push(
            '  const response = await responsePromise;',
            '  expect(response.status()).toBeLessThan(500);',
          );
          break;
      }
    }
    lines.push('});', '');
    return lines.join('\n');
  }
}
