import { access, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { FileTargetProject } from '../../src/infrastructure/file-target-project.js';
import type { ExportEntry } from '../../src/domain/export.js';

const temporaryDirectories: string[] = [];

async function temporary(prefix: string): Promise<string> {
  const value = await mkdtemp(join(tmpdir(), prefix));
  temporaryDirectories.push(value);
  return value;
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

describe('FileTargetProject', () => {
  it('statically inspects a TypeScript Playwright project without executing hostile config', async () => {
    const root = await temporary('agentic-qa-target-');
    const marker = join(root, 'must-not-exist');
    await mkdir(join(root, 'tests'));
    await writeFile(
      join(root, 'package.json'),
      JSON.stringify({
        name: '$(touch should-not-run)',
        type: 'module',
        devDependencies: { '@playwright/test': '1', typescript: '1' },
      }),
    );
    await writeFile(join(root, 'package-lock.json'), '{}');
    await writeFile(join(root, 'tsconfig.json'), '{}');
    await writeFile(
      join(root, 'playwright.config.ts'),
      `throw new Error('must not execute');\nconst marker = ${JSON.stringify(marker)};\nexport default { testDir: './tests', use: { baseURL: 'https://example.test' } };`,
    );
    const profile = await new FileTargetProject().inspect(root);
    expect(profile).toMatchObject({
      packageManager: 'npm',
      playwrightDependency: true,
      configuredTestDirectory: './tests',
      configuredBaseUrl: 'https://example.test',
      language: 'typescript',
    });
    await expect(access(marker)).rejects.toThrow();
  });

  it('rejects an export path when any parent symlink can escape the target', async () => {
    const root = await temporary('agentic-qa-target-');
    const outside = await temporary('agentic-qa-outside-');
    await mkdir(join(root, 'tests'));
    await symlink(outside, join(root, 'tests', 'agentic-qa'));
    await expect(
      new FileTargetProject().inspectDestination(root, 'tests/agentic-qa/DEF-12345678.spec.ts'),
    ).rejects.toThrow(/symlink escape/i);
    await expect(access(join(outside, 'DEF-12345678.spec.ts'))).rejects.toThrow();
  });

  it('uses create-exclusive writes and requires overwrite for a conflict', async () => {
    const root = await temporary('agentic-qa-target-');
    await mkdir(join(root, 'tests', 'agentic-qa'), { recursive: true });
    const destination = 'tests/agentic-qa/DEF-12345678.spec.ts';
    await writeFile(join(root, destination), '// human file\n');
    const source = '// Generated by Agentic QA.\nexport {};\n';
    const digest = (await import('node:crypto')).createHash('sha256').update(source).digest('hex');
    const entry: ExportEntry = {
      findingId: 'DEF-12345678',
      source: 'tests/DEF-12345678.spec.ts',
      destination,
      status: 'CONFLICT',
      sourceDigest: digest,
      existingDigest: null,
      diff: null,
      willWrite: false,
      reason: 'conflict',
    };
    const target = new FileTargetProject();
    const skipped = await target.apply(root, [entry], new Map([[entry.source, source]]), false);
    expect(skipped[0]?.action).toBe('SKIPPED');
    expect(await readFile(join(root, destination), 'utf8')).toBe('// human file\n');
    const replaced = await target.apply(root, [entry], new Map([[entry.source, source]]), true);
    expect(replaced[0]?.action).toBe('OVERWRITTEN');
    expect(await readFile(join(root, destination), 'utf8')).toBe(source);
  });

  it('never invokes a shell when validation receives metacharacters in a path', async () => {
    const root = await temporary('agentic-qa-target-;$(safe)-');
    const result = await new FileTargetProject().validate(
      root,
      'unknown',
      ['tests/agentic-qa/DEF-12345678.spec.ts;touch-pwned'],
      1_000,
    );
    expect(result.status).toBe('NOT_AVAILABLE');
    await expect(access(join(root, 'touch-pwned'))).rejects.toThrow();
  });
});
